services:
  smngt:
    build:
      context: .
      dockerfile: Dockerfile
    image: smngt
    container_name: smngt_container
    ports:
      - "8080:8080"
    environment:
      - MICRONAUT_SERVER_PORT=8080
    restart: always